---
- name: Set hostname for node
  hostname:
    name: "{{ node_name }}"
  tags:
    - hostname

- name: Update hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts 
    line: '127.0.0.1 {{node_name}}' 
    state: present 
    backup: yes
  tags:
    - hostname