---
- name: Restart rabbitmq
  service:
    name: rabbitmq-server
    state: restarted
  tags:
    - rabbitmq

- name: Reload daemon
  systemd:
    state: restarted
    daemon_reload: yes
    name: rabbitmq-server